owner: goeckslab
description: "Cell type identification with spatial information"
long_description: |
  CELESTA (CELl typE identification with SpaTiAl information) is an 
  algorithm aiming to perform automate cell type identification for 
  multiplexed in situ imaging data. CELESTA makes use of both protein 
  expressions and cell spatial neighborhood information from segmented 
  imaging data for the cell type identification.
categories:
  - Imaging
  - Proteomics
exclude:
  - dependencies
remote_repository_url: https://github.com/goeckslab/tools-mti/tree/main/tools/celesta
homepage_url: https://github.com/plevritis-lab/CELESTA
