owner: goeckslab
homepage_url: https://squidpy.readthedocs.io/en/stable/
remote_repository_url: https://github.com/goeckslab/tools-mti/tree/main/tools/squidpy
description: Squidpy is a tool for the analysis and visualization of spatial molecular data.
long_description: |
  Squidpy is a tool for the analysis and visualization of spatial molecular data. 
  It builds on top of scanpy and anndata, from which it inherits modularity and scalability. 
  It provides analysis tools that leverages the spatial coordinates of the data, 
  as well as tissue images if available.
categories:
  - Imaging
  - Proteomics
  - Transcriptomics
  - Visualization
exclude:
  - dependencies
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for Squidpy tool: {{ tool_name }}"
suite:
  name: suite_squidpy
  description: Squidpy is a tool for the analysis and visualization of spatial molecular data.
  long_description: |
    Squidpy is a tool for the analysis and visualization of spatial molecular data. 
    It builds on top of scanpy and anndata, from which it inherits modularity and scalability. 
    It provides analysis tools that leverages the spatial coordinates of the data, 
    as well as tissue images if available.