owner: goeckslab
remote_repository_url: https://github.com/goeckslab/tools-mti/tree/main/tools/mti-utils
homepage_url: https://github.com/goeckslab/tools-mti/tree/main/tools/mti-utils
long_description: |
    A suite of tool wrapper for Multiplex Tissue Imaging (MTI) utilities.
    These include simple custom scripts for renaming channels in OME-TIFF metadata, 
    and singal-processing for tabular intensity data. More utilities may be added in
    the future. 
categories:
  - Imaging
exclude:
  - dependencies
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for MTI Utility: {{ tool_name }}"
suite:
  name: suite_mti_utils
  description: "A suite of tool wrappers for Multiplex Tissue Imaging (MTI) utilities"
  long_description: |
    A suite of tool wrapper for Multiplex Tissue Imaging (MTI) utilities.
    These include simple custom scripts for renaming channels in OME-TIFF metadata, 
    and singal-processing for tabular intensity data. More utilities may be added in
    the future. 
